name: Release Package

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: [self-hosted, Linux]
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v4

            - name: Install Rokit
              uses: CompeyDev/setup-rokit@v0.1.2

            - uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@paradoxum-games'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build Package
              run: rojo build --output Lyra.rbxm build.project.json

            - name: Create Release
              run: gh release create $GITHUB_REF_NAME --generate-notes
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Upload Release Asset
              run: gh release upload $GITHUB_REF_NAME Lyra.rbxm
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Publish to GitHub Packages
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    docs:
        needs: release
        permissions:
            contents: write
        uses: ./.github/workflows/publish-docs.yml
        secrets: inherit
